### ISSUE TITLE
Issue publishing to MQTT broker (detected with motion sample agent)

### ISSUE THREAD

**Issue by oleksandr** [patchwork-toolkit/patchwork#21]

**Comment by oleksandr** [comment]
Something is blocking publications. No data from "motion" agent is available via REST/MQTT. When the DGW is shutdown the following appears in log:

```
[device-gateway] 16:19:51 MQTTPublisher.stop()
[device-gateway] 16:19:51 MQTTPublisher: published to /pw/dgw/octopus/Alarm/MotionDetector
[device-gateway] 16:19:52 Stopped
```

**Comment by krylovsk** [comment]
It seems that the connect() call to the MQTTPublisher also blocks. 
For example, when network connection to broker is not available, upon starting dgw initialisation blocks on it:
[device-gateway] 19:33:45 MQTTPublisher.connect()
