### ISSUE TITLE
Lookup catalog once it went offline (see comments)

### ISSUE THREAD

**Issue by oleksandr** [patchwork-toolkit/patchwork#32]

**Comment by oleksandr** [comment]
DGW discovers DC. When DC goes offline DGW simply outputs:

[device-gateway] 23:46:55 Error accessing the catalog: Put http://shanti.fritz.box.:8081/dc/my-demo-gateway-1/System: dial tcp 10.0.0.22:8081: connection refused
[device-gateway] 23:46:55 Error accessing the catalog: Put http://shanti.fritz.box.:8081/dc/my-demo-gateway-1/DummyDevice: dial tcp 10.0.0.22:8081: connection refused

It would be nice to have automatic discovery of the catalog again once disconnected and some timeouts (retries).

The same is related to DC discovering SC.
The same is related to registration utility.

**Comment by krylovsk** [comment]
Should work now. Implemented for both SC and DC in catalog/<device,service>/utils
