### ISSUE TITLE
Add DGW's support for discovering MQTT broker via DNS-SD 

### ISSUE THREAD

**Issue by oleksandr** [patchwork-toolkit/patchwork#5]

**Comment by oleksandr** [comment]
This is a follow-up task when #4 is done

**Comment by oleksandr** [comment]
Can we rely here on SDK?

**Comment by krylovsk** [comment]
Do we really need that? Isn't the idea that we use Service Catalog to discover everything but the SC itself?

**Comment by oleksandr** [comment]
Implementing using the remote SC client API actually
